services:
  backend:
    build: .
    image: money-tracker/backend
    container_name: backend
    env_file:
      - path: .env
        required: true
    environment:
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data/pgdata
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

  nginx:
    image: nginx:1.26
    container_name: nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/certs/backend.crt:/etc/nginx/conf.d/backend.crt
      - ./config/certs/backend.csr:/etc/nginx/conf.d/backend.csr
      - ./config/certs/backend.key:/etc/nginx/conf.d/backend.key
      - ./config/certs/backend.pem:/etc/nginx/conf.d/backend.pem
    ports:
      - "80:80"
      - "443:443"

  metrics:
    image: victoriametrics/victoria-metrics:v1.101.0
    container_name: metrics
    command:
      - "-promscrape.config=scrape.yaml"
    volumes:
      - ./config/metrics/scrape.yaml:/scrape.yaml
      - ./data/victoria-metrics-data:/victoria-metrics-data
    ports:
      - "8428:8428"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana-oss:11.0.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"

networks:
  backend:
