include:
  - ./config/idp/compose.yml
  - ./config/monitoring/compose.yml

services:
  backend:
    build: .
    image: money-tracker/backend
    profiles: [ backend ]
    container_name: backend
    env_file:
      - path: .env
        required: true
    environment:
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    profiles: [ backend ]
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ${DATA}/pg:/var/lib/postgresql/data/pgdata
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  nginx:
    profiles: [ backend ]
    image: nginx:1.26
    container_name: nginx
    depends_on:
      - backend
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/certs/backend.crt:/etc/nginx/conf.d/backend.crt
      - ./config/certs/backend.csr:/etc/nginx/conf.d/backend.csr
      - ./config/certs/backend.key:/etc/nginx/conf.d/backend.key
      - ./config/certs/backend.pem:/etc/nginx/conf.d/backend.pem
    ports:
      - "80:80"
      - "443:443"

networks:
  backend:
