version: '3.8'

services:
  backend:
    build: .
    image: money-tracker/backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

  nginx:
    image: nginx:1.26
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./crt/backend.crt:/etc/nginx/conf.d/backend.crt
      - ./crt/backend.csr:/etc/nginx/conf.d/backend.csr
      - ./crt/backend.key:/etc/nginx/conf.d/backend.key
      - ./crt/backend.pem:/etc/nginx/conf.d/backend.pem
    ports:
      - "80:80"
      - "443:443"

networks:
  backend:
