services:

  metrics:
    profiles: [ monitoring ]
    image: victoriametrics/victoria-metrics:v1.101.0
    container_name: metrics
    command:
      - "-promscrape.config=scrape.yaml"
    volumes:
      - ./scrape.yaml:/scrape.yaml
      - ${DATA_2_LVL_UP}/victoria-metrics-data:/victoria-metrics-data
    ports:
      - "8428:8428"

  grafana:
    profiles: [ monitoring ]
    image: grafana/grafana-oss:11.0.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - ${DATA_2_LVL_UP}/grafana:/var/lib/grafana
    ports:
      - "3000:3000"