scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: [ "backend:8080" ]
    metrics_path: "/actuator/prometheus"
  - job_name: "postgres"
    static_configs:
      - targets: [ "pg-exporter:9187" ]