spring:
  datasource:
    url: ${db.url:jdbc:postgresql://localhost:5432/money_tracker}
    username: ${db.username}
    password: ${db.password}
  liquibase:
    change-log: classpath:/db/changelog-master.xml
