spring:
  datasource:
    url: ${db.url:jdbc:postgresql://localhost:5432/money_tracker}
    username: ${db.username}
    password: ${db.password}
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${introspection.uri}
          client-id: ${client.id}
          client-secret: ${client.secret}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  metrics:
    tags:
      application: backend
